### ISSUE TITLE
[NPCs] npc_lightstalk feature request

### ISSUE THREAD

**Issue by DontMakeLemonade** [entropy-zero/source-sdk-2013#18]
**npc_lightstalk Feature Request**

The Light Stalk is an NPC used in EZ2, a piece of Xen flora which illuminates its surroundings and hides when approached.
I am submitting this GutHub issue to request this NPC in the EZ1 Mapbase code for use in Cleanup : Zero.
Here is a link to Cleanup : Zero on Moddb, and the latest article: https://www.moddb.com/mods/cleanup-zero/news/december-2021-update1

**Purpose**

This would be a great addition to Cleanup : Zero as the already existing Light Stalk is simply made up of a trigger and a model, this is an issue because it is very easily broken just by activating the trigger a couple times in a short time span. This causes the model's animations to start repeating randomly as well as the sounds and light entity tied to the trigger. I have tried multiple different trigger systems to create a functional Light Stalk and all of which seem to break very quickly.

**Comment by 1upD** [comment]
@DontMakeLemonade I believe this is no longer needed, correct? I think it was a reasonable request but from what I understand Contamination : Zero has moved to EZ2. Sorry for not clearing this up sooner!
