### ISSUE TITLE
[TOOLS] Tags Localization Support For Workshop Publisher

### ISSUE THREAD

**Issue by IBRS-4Ever** [entropy-zero/source-sdk-2013#182]
### Is your feature request related to a problem? Please describe.
Make tags support localization (Sound, Script, Item, etc).

**Comment by 1upD** [comment]
Looking at other Steam workshops such as Left 4 Dead 2, it doesn't look like Steam workshop tags support localization.

**Comment by IBRS-4Ever** [comment]
as far as I know, there's one workshop that supports localization: Codename Cure.
