### ISSUE TITLE
[GAME] mape load error

### ISSUE THREAD

**Issue by breakdowngamesYT** [entropy-zero/source-sdk-2013#190]
when i try to load a map the screen flashes and im still in the menu

compile ez2 code
launch it on steam
open the console and try to load a map

the map loads

---

this is what the consol does

map lighting
Can't find bonus files
Mapbase system loaded
CLocalizedStringTable::AddFile() failed to load file "resource/mapbase_english.txt".
VSCRIPT SERVER: Started VScript virtual machine using script language 'squirrel'
Script not found (scripts/vscripts/vscript_server.nut) 
Error reading weapon data file for: weapon_custom_scripted1
Error reading weapon data file for: weapon_slam
Error reading weapon data file for: weapon_smg2
Error reading weapon data file for: weapon_endgame
Error reading weapon data file for: weapon_arbeit_shotgun
Error reading weapon data file for: weapon_css_xm1014
Error reading weapon data file for: weapon_css_m3
Error reading weapon data file for: weapon_sniperrifle
Attempting to precache model, but model name is NULL
Attempting to precache model, but model name is NULL
Error reading weapon data file for: weapon_pulsepistol
Error reading weapon data file for: weapon_arbeit_clipboard
Error reading weapon data file for: weapon_ar2_proto
Error reading weapon data file for: weapon_displacer_pistol
ERROR: Weapon (weapon_manhacktoss) using undefined primary ammo type (Manhack)
Error: Material "models/combine_soldier/armor_chest" uses unknown shader "SDK_VertexLitGeneric"
Error: Material "models/combine_soldier/armor_strap" uses unknown shader "SDK_VertexLitGeneric"
Error: Material "models/combine_soldier/armor_thigh_r" uses unknown shader "SDK_VertexLitGeneric"
Error: Material "models/combine_soldier/armor_thigh_l" uses unknown shader "SDK_VertexLitGeneric"
Error: Material "models/combine_soldier/armor_arm" uses unknown shader "SDK_VertexLitGeneric"
'cfg/motd.txt' not found; not loaded
'cfg/motd_text.txt' not found; not loaded
Attemped to precache unknown particle system "hgib"!
Attemped to precache unknown particle system "red_spawn"!
Attemped to precache unknown particle system "blue_spawn"!
Attemped to precache unknown particle system "headcrab_gib"!
DataTable warning: No matching RecvTable for SendTable 'DT_Base_CSS_HL2_MachineGun'.
DataTable warning: No matching RecvTable for SendTable 'DT_Base_CSS_HL2_Pistol'.
DataTable warning: No matching RecvTable for SendTable 'DT_Base_CSS_HL2_Shotgun'.
DataTable warning: No matching RecvTable for SendTable 'DT_Base_CSS_HL2_SniperRifle'.
DataTable warning: No matching RecvTable for SendTable 'DT_DisplacerPistol'.
DataTable warning: No matching RecvTable for SendTable 'DT_EnvDOFController'.
DataTable warning: No matching RecvTable for SendTable 'DT_EZ2_Player'.
DataTable warning: No matching RecvTable for SendTable 'DT_FuncClientClip'.
DataTable warning: No matching RecvTable for SendTable 'DT_FuncFakeWorldPortal'.
DataTable warning: No matching RecvTable for SendTable 'DT_GlobalLight'.
DataTable warning: No matching RecvTable for SendTable 'DT_HandViewModel'.
DataTable warning: No matching RecvTable for SendTable 'DT_LogicScriptClient'.
DataTable warning: No matching RecvTable for SendTable 'DT_MapbaseMetadata'.
DataTable warning: No matching RecvTable for SendTable 'DT_MovieDisplay'.
DataTable warning: No matching RecvTable for SendTable 'DT_NPC_Advisor'.
DataTable warning: No matching RecvTable for SendTable 'DT_NPC_Arbeit_FloorTurret'.
DataTable warning: No matching RecvTable for SendTable 'DT_NPC_Wilson'.
DataTable warning: No matching RecvTable for SendTable 'DT_PlayerViewProxy'.
DataTable warning: No matching RecvTable for SendTable 'DT_PointCameraOrtho'.
DataTable warning: No matching RecvTable for SendTable 'DT_PointGlow'.
DataTable warning: No matching RecvTable for SendTable 'DT_PostProcessController'.
DataTable warning: No matching RecvTable for SendTable 'DT_SatchelCharge'.
DataTable warning: No matching RecvTable for SendTable 'DT_TripmineGrenade'.
DataTable warning: No matching RecvTable for SendTable 'DT_VGuiTextDisplay'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_Arbeit_Pistol'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_Arbeit_Shotgun'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_AK47'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_AUG'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_AWP'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_Deagle'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_DualBerettas'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_FAMAS'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_FiveSeveN'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_G3SG1'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_Galil'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_Glock18'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_M249'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_M3'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_M4A1'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_MAC10'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_MP5Navy'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_P228'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_P90'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_Scout'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_SG550'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_SG552'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_TMP'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_UMP45'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_USP'.
DataTable warning: No matching RecvTable for SendTable 'DT_Weapon_CSS_HL2_XM1014'.
DataTable warning: No matching RecvTable for SendTable 'DT_WeaponAR2Proto'.
DataTable warning: No matching RecvTable for SendTable 'DT_WeaponArbeitClipboard'.
DataTable warning: No matching RecvTable for SendTable 'DT_WeaponCustomScripted'.
DataTable warning: No matching RecvTable for SendTable 'DT_WeaponEndGame'.
DataTable warning: No matching RecvTable for SendTable 'DT_WeaponFlechetteShotgun'.
DataTable warning: No matching RecvTable for SendTable 'DT_WeaponPulsePistol'.
DataTable warning: No matching RecvTable for SendTable 'DT_WeaponSniperRifle'.
DataTable warning: No matching RecvTable for SendTable 'DT_WeaponStasisGrenade'.
Client missing DT class CBase_CSS_HL2_MachineGun
Client missing DT class CBase_CSS_HL2_Pistol
Client missing DT class CBase_CSS_HL2_Shotgun
Client missing DT class CBase_CSS_HL2_SniperRifle
Client missing DT class CDisplacerPistol
Client missing DT class CEnvDOFController
Client missing DT class CEZ2_Player
Client missing DT class CFuncClientClip
Client missing DT class CFuncFakeWorldPortal
Client missing DT class CGlobalLight
Client missing DT class CHandViewModel
Client missing DT class CLogicScriptClient
Client missing DT class CMapbaseMetadata
Client missing DT class CMovieDisplay
Client missing DT class CNPC_Advisor
Client missing DT class CNPC_Arbeit_FloorTurret
Client missing DT class CNPC_Wilson
Client missing DT class CPlayerViewProxy
Client missing DT class CPointCameraOrtho
Client missing DT class CPointGlow
Client missing DT class CPostProcessController
Client missing DT class CSatchelCharge
Client missing DT class CTripmineGrenade
Client missing DT class CVGuiTextDisplay
Client missing DT class CWeapon_Arbeit_Pistol
Client missing DT class CWeapon_Arbeit_Shotgun
Client missing DT class CWeapon_CSS_HL2_AK47
Client missing DT class CWeapon_CSS_HL2_AUG
Client missing DT class CWeapon_CSS_HL2_AWP
Client missing DT class CWeapon_CSS_HL2_Deagle
Client missing DT class CWeapon_CSS_HL2_DualBerettas
Client missing DT class CWeapon_CSS_HL2_FAMAS
Client missing DT class CWeapon_CSS_HL2_FiveSeveN
Client missing DT class CWeapon_CSS_HL2_G3SG1
Client missing DT class CWeapon_CSS_HL2_Galil
Client missing DT class CWeapon_CSS_HL2_Glock18
Client missing DT class CWeapon_CSS_HL2_M249
Client missing DT class CWeapon_CSS_HL2_M3
Client missing DT class CWeapon_CSS_HL2_M4A1
Client missing DT class CWeapon_CSS_HL2_MAC10
Client missing DT class CWeapon_CSS_HL2_MP5Navy
Client missing DT class CWeapon_CSS_HL2_P228
Client missing DT class CWeapon_CSS_HL2_P90
Client missing DT class CWeapon_CSS_HL2_Scout
Client missing DT class CWeapon_CSS_HL2_SG550
Client missing DT class CWeapon_CSS_HL2_SG552
Client missing DT class CWeapon_CSS_HL2_TMP
Client missing DT class CWeapon_CSS_HL2_UMP45
Client missing DT class CWeapon_CSS_HL2_USP
Client missing DT class CWeapon_CSS_HL2_XM1014
Client missing DT class CWeaponAR2Proto
Client missing DT class CWeaponArbeitClipboard
Client missing DT class CWeaponCustomScripted
Client missing DT class CWeaponEndGame
Client missing DT class CWeaponFlechetteShotgun
Client missing DT class CWeaponPulsePistol
Client missing DT class CWeaponSniperRifle
Client missing DT class CWeaponStasisGrenade
Missing RecvProp for DT_AR2Explosion - DT_BaseEntity/m_iViewHideFlags
Host_EndGame: CL_ParseClassInfo_EndClasses: CreateDecoders failed.

Saving d:\steamlibrary\steamapps\common\entropy zero\entropy zero\entropyzero\sound\sound.cache
Dropped breakdowngames from server (Disconnect by user.)

**Comment by Blixibon** [comment]
I'm noticing two issues here:

1. It seems like the server DLL is out of sync with the client DLL. If you already have that in your mod's `bin` folder, it's possible that the latter is somehow failing to load. A common reason is that it's looking for the Discord RPC DLL and is failing to find it. You could try going to `steamapps/common/EntropyZero2/entropyzero2/bin` and copying `discord-rpc.dll` to your mod's `bin` folder.
2. According to some of these messages, your mod appears to be based off of the original Entropy : Zero rather than Entropy : Zero 2. If you downloaded the [Entropy : Zero Mod Template](https://github.com/entropy-zero/source-sdk-2013/releases/tag/EZ1v4.0), that wasn't designed to be used with E:Z2. To my knowledge, its spiritual successor is the [Entropy : Zero 2 Addon Workspace](https://github.com/entropy-zero/entropyzero2-addonworkspace), a much simpler template designed to be used to create Steam Workshop addons, although I might need @1upD to confirm it can be used for whatever you're doing with custom code.

**Comment by breakdowngamesYT** [comment]
i just downloaded the source code

**Comment by breakdowngamesYT** [comment]
should i be using a different branch or

**Comment by Blixibon** [comment]
Did you follow my instructions?

**Comment by breakdowngamesYT** [comment]
i mean like should i use a branch of the code like master or ez2-mapbase-7.0

**Comment by Blixibon** [comment]
`ez2/mapbase` is the branch for the latest E:Z2 code.

**Comment by breakdowngamesYT** [comment]
k
