### ISSUE TITLE
[GAME] Tertiary fire for mass-produced, 30 shots in one shell AR2

### ISSUE THREAD

**Issue by Vlad-Melnichuk** [entropy-zero/source-sdk-2013#232]
### Is your feature request related to a problem? Please describe.
I think the fact that the mass-produced (non-prototype) AR2 has 30 shots chambered in a single shell would add versatility to the weapon.

### Describe the solution you'd like
I deem it would be great to have the tertiary attack button like in RTBR, series "30-shots-in-one-shell" AR2's tertiary attack firing a supershot with powerful recoil animation, consuming `int tertiary_shot_charge = MIN (10, m_iClip1)` ammo amount, increasing all `m_flNextPrimaryAttack`, `m_flNextSecondaryAttack` and `m_flNextTertiaryAttack` times by, say, 1 second and itself being one of two options:
1) a powerful superbullet with precision like primary fire, `tertiary_shot_charge` damage multiplier related to primary shot and a special thick and bright tracer or
2) a pulse shotgun blast with `tertiary_shot_charge` pellets each being similar to primary shot.

The player should be able to decide freely between the series and prototype AR2s and swap them vice versa freely.
In case of replacing the prototype back to mass-produced AR2 Bad Cop should say something like "I'd rather keep the super shot".

**Comment by 1upD** [comment]
This request would be an opinionated change to the design of the game. I could understand if this is for a separate mod but this isn't something that would be a good fit for EZ2. Additionally, the tertiary fire function is already used for the kick.
