### ISSUE TITLE
[CODE] Maps Wont Load 

### ISSUE THREAD

**Issue by valina354** [entropy-zero/source-sdk-2013#242]
### Describe the bug
maps dont load

### Steps to reproduce
1. Compile EZ2 code
2. put compiled dlls in a source mod
3. See error

### Expected behavior
maps wont load and a lot of errors

![image](https://github.com/entropy-zero/source-sdk-2013/assets/80889633/16856deb-e177-42f9-8a4b-e521c0c64147)

**Comment by 1upD** [comment]
This error is not reproducible with the steps provided
